import re

file_path = '/Users/amritpaudel/Downloads/EcoTracer/ecotrace/client/src/pages/AiAssistant.jsx'

with open(file_path, 'r') as f:
    content = f.read()

# 1. Add imports at the top
import_old = "import React, { useState, useRef, useEffect } from 'react';"
import_new = "import React, { useState, useRef, useEffect } from 'react';\nimport { aiService, mockData } from '../services/api';"
if "import { aiService, mockData }" not in content:
    content = content.replace(import_old, import_new)

# 2. Replace getAIResponse and handleSend
# First, remove getAIResponse entirely
ai_response_regex = re.compile(r'  // Process and generate simulated AI responses.*?return response;\n  };\n\n', re.DOTALL)
content = re.sub(ai_response_regex, '', content)

# Now, replace handleSend
handle_send_regex = re.compile(r'  const handleSend = \(\) => \{.*?\}, 1500\);\n  };\n', re.DOTALL)
handle_send_new = """  const handleSend = async () => {
    if (!inputText.trim() && !attachedFile) return;

    const userMsg = {
      id: Date.now(),
      sender: 'user',
      text: inputText,
      file: attachedFile ? { name: attachedFile.name, type: attachedFile.type } : null
    };

    setMessages((prev) => [...prev, userMsg]);
    
    // Build query for Gemini
    let queryText = inputText;
    if (attachedFile) {
        queryText = `[User attached file: ${attachedFile.name}] ${queryText}`;
    }

    setInputText('');
    setAttachedFile(null);
    setIsTyping(true);

    try {
      // Gather context from mockData
      const context = {
        farm: mockData.farms[0],
        weather: mockData.weather,
        sustainability: mockData.sustainability,
        carbonCredits: {
            available: mockData.carbonCredits.credits_available,
            price: mockData.carbonCredits.price_per_credit
        }
      };

      const response = await aiService.askAiAssistant(queryText, lang === 'en' ? 'English' : 'Nepali', context);
      
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + 1,
          sender: 'ai',
          text: response.text,
          confidence: response.confidence || 98,
          references: response.references || ["Generated by Krishi Saarathi AI (Gemini 2.5 Flash)"],
          followups: response.followups || []
        }
      ]);
    } catch (error) {
      console.error("AI Assistant Error:", error);
      const errorMsg = lang === 'en' 
        ? `<h4 class="font-bold text-red-700 flex items-center gap-2 mb-3">⚠️ Service Unavailable</h4>
           <p>I'm sorry, I am currently unable to connect to the AI server. Please check your internet connection or try again later.</p>`
        : `<h4 class="font-bold text-red-700 flex items-center gap-2 mb-3">⚠️ सेवा उपलब्ध छैन</h4>
           <p>माफ गर्नुहोस्, म अहिले एआई सर्भरमा जडान गर्न असमर्थ छु। कृपया आफ्नो इन्टरनेट जाँच गर्नुहोस् वा पछि प्रयास गर्नुहोस्।</p>`;
           
      setMessages((prev) => [
        ...prev,
        {
          id: Date.now() + 1,
          sender: 'ai',
          text: errorMsg,
          confidence: 0,
          references: [],
          followups: []
        }
      ]);
    } finally {
      setIsTyping(false);
    }
  };
"""

content = re.sub(handle_send_regex, handle_send_new, content)

with open(file_path, 'w') as f:
    f.write(content)

print("Updated handleSend successfully.")
