from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, Any
from google import genai
from google.genai import types

from app.config import settings

router = APIRouter()

class ChatRequest(BaseModel):
    query: str
    language: str
    context: Optional[dict[str, Any]] = None

@router.post("/chat")
async def chat_with_ai(request: ChatRequest):
    if not settings.gemini_api_key:
        raise HTTPException(
            status_code=503, 
            detail="AI service is currently unavailable. GEMINI_API_KEY is not configured."
        )
    
    try:
        client = genai.Client(api_key=settings.gemini_api_key)
        
        # Build the system instruction
        system_instruction = (
            "You are Krishi Saarathi AI, an expert agricultural assistant specializing in "
            "Nepali agriculture, sustainability, carbon credits, insurance claims, livestock, "
            "irrigation, soil science, and marketplace guidance.\n\n"
            "Guidelines:\n"
            "1. You must respond in the language requested by the user.\n"
            "2. Always structure your responses using HTML format compatible with Tailwind CSS.\n"
            "3. Use the following structured headings (use <h4> tags with appropriate emojis) if applicable: "
            "Summary, Analysis, Recommendations, Best Practices, and Additional Notes.\n"
            "4. Do NOT wrap your output in markdown code blocks (like ```html). Output raw HTML directly so it can be injected via dangerouslySetInnerHTML.\n"
            "5. If the user asks a general question, answer it naturally but concisely.\n"
            "6. Use the provided farm context to give personalized advice when relevant.\n\n"
            "Output Format Example:\n"
            "<h4 class='font-bold text-emerald-700 flex items-center gap-2 mb-3'>📋 Summary</h4>\n"
            "<p class='mb-2'>...</p>\n"
            "<h4 class='font-bold text-emerald-700 flex items-center gap-2 mb-3'>🔍 Analysis</h4>\n"
            "<p class='mb-2'>...</p>\n"
            "<h4 class='font-bold text-emerald-700 flex items-center gap-2 mb-3'>✅ Recommendations</h4>\n"
            "<ul class='list-disc pl-5 space-y-1 mb-2'><li>...</li></ul>\n"
        )
        
        # Build the user prompt
        prompt = f"User Language Preference: {request.language}\n"
        if request.context:
            prompt += f"Farm Context:\n{request.context}\n\n"
        prompt += f"User Query: {request.query}"

        # Call Gemini 2.5 Flash
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.3,
            )
        )
        
        # Clean up any potential markdown code blocks that the LLM might stubbornly return
        response_text = response.text.strip()
        if response_text.startswith("```html"):
            response_text = response_text[7:]
        if response_text.startswith("```"):
            response_text = response_text[3:]
        if response_text.endswith("```"):
            response_text = response_text[:-3]
        
        return {
            "text": response_text.strip(),
            "confidence": 98,
            "references": ["Generated by Krishi Saarathi AI (Gemini 2.5 Flash)"],
            "followups": [] 
        }
        
    except Exception as e:
        print(f"Gemini API Error: {str(e)}")
        raise HTTPException(
            status_code=500, 
            detail=f"An error occurred while communicating with the AI service: {str(e)}"
        )
